#!/usr/bin/env python3
"""
Generate cross-temperature "turn layer" heatmaps for the paper.

Turn layer = first layer where SVP > TVP (social projection exceeds truth projection).

Inputs:
- Per-run `turn_layer_statistics.csv` generated by `Analysis Scripts/generate_figure3_turn_layer.py`
  under `runs-hpc-full/probe/runs/<timestamp>_<run_id>/artifacts/tables/`.

Outputs:
- paper/figures/turn_layer_by_temperature.png
- paper/figures/turn_layer_by_temperature.pdf
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns


VARIANT_ORDER = ["base", "instruct", "instruct_sft", "think", "think_sft", "rl_zero"]
VARIANT_LABELS = {
    "base": "Base",
    "instruct": "Instruct",
    "instruct_sft": "Instruct-SFT",
    "think": "Think",
    "think_sft": "Think-SFT",
    "rl_zero": "RL-Zero",
}

TEMP_ORDER = [0.0, 0.2, 0.4, 0.6, 0.8, 1.0]
TEMP_LABELS = {t: f"T={t:.1f}" for t in TEMP_ORDER}

COND_ORDER = ["asch_history_5", "authoritative_bias"]
COND_TITLES = {"asch_history_5": "Asch (5)", "authoritative_bias": "Authority"}


DEFAULT_RUN_IDS: Dict[float, str] = {
    0.0: "56478e99-7607-4957-9f53-a53b73a7e9d4",
    0.2: "99127619-fcc7-4fd4-ba3a-cc810610249f",
    0.4: "271bb5b2-572d-4ecd-8577-b07a7cd10846",
    0.6: "dda9d6b3-a516-41b3-a85a-b424de8f15d3",
    0.8: "eb777acc-3ab5-4f87-b073-249a50d25863",
    1.0: "fa0b1d4f-d547-4094-b07c-4f9efc20f771",
}


def _find_run_dir(*, runs_dir: Path, run_id: str) -> Path:
    matches = sorted(runs_dir.glob(f"*_{run_id}"), key=lambda p: p.name, reverse=True)
    if not matches:
        raise FileNotFoundError(f"Could not find run_dir under {runs_dir} ending with _{run_id}")
    return matches[0]


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Generate turn-layer heatmaps across temperatures.")
    p.add_argument("--runs-dir", type=str, default="runs-hpc-full/probe/runs")
    p.add_argument("--out-dir", type=str, default="paper/figures")
    args = p.parse_args(argv)

    runs_dir = Path(args.runs_dir).resolve()
    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    rows = []
    for temp, run_id in DEFAULT_RUN_IDS.items():
        run_dir = _find_run_dir(runs_dir=runs_dir, run_id=run_id)
        stats_path = run_dir / "artifacts" / "tables" / "turn_layer_statistics.csv"
        if not stats_path.exists():
            raise FileNotFoundError(f"Missing {stats_path} (run_id={run_id})")
        df = pd.read_csv(stats_path)
        df["temperature"] = float(temp)
        rows.append(df)

    all_df = pd.concat(rows, ignore_index=True)
    all_df = all_df[all_df["condition_name"].isin(COND_ORDER)].copy()

    # Plot
    sns.set_style("white")
    fig, axes = plt.subplots(1, 2, figsize=(11.5, 4.2), constrained_layout=True)
    vmin, vmax = 0.0, 31.0

    for ax, cond in zip(axes, COND_ORDER):
        sub = all_df[all_df["condition_name"] == cond].copy()
        pivot = (
            sub.pivot(index="variant", columns="temperature", values="mean_first_collision_layer")
            .reindex(index=VARIANT_ORDER, columns=TEMP_ORDER)
        )

        sns.heatmap(
            pivot,
            ax=ax,
            cmap="viridis",
            vmin=vmin,
            vmax=vmax,
            cbar=ax is axes[-1],
            cbar_kws={"label": "Mean first collision layer"},
            annot=True,
            fmt=".1f",
            linewidths=0.5,
            linecolor="white",
        )

        ax.set_title(COND_TITLES.get(cond, cond))
        ax.set_xlabel("Temperature")
        ax.set_ylabel("Variant" if ax is axes[0] else "")

        ax.set_xticklabels([TEMP_LABELS.get(float(t), str(t)) for t in pivot.columns], rotation=45, ha="right")
        ax.set_yticklabels([VARIANT_LABELS.get(v, v) for v in pivot.index], rotation=0)

    fig.suptitle("Turn Layer Across Temperature (SVP > TVP)")

    png_path = out_dir / "turn_layer_by_temperature.png"
    pdf_path = out_dir / "turn_layer_by_temperature.pdf"
    fig.savefig(png_path, dpi=300)
    fig.savefig(pdf_path)
    plt.close(fig)

    print(str(png_path))
    print(str(pdf_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

